const TOPLANE_CHAMPIONS = [
  {
    id: 'Aatrox',
    name: 'Aatrox',
    role: 'Top',
    tags: ['Engage', 'Juggernaut'],
    stats: { range: 2, burst: 6, cc: 7, mobility: 4, waveclear: 8, scaling: 6 },
    synergies: ['CC_Chain', 'Frontline'],
  },
  {
    id: 'Akali',
    name: 'Akali',
    role: 'Top',
    tags: ['Assassin', 'Skirmisher'],
    stats: { range: 1, burst: 9, cc: 2, mobility: 9, waveclear: 6, scaling: 7 },
    synergies: ['Dive', 'Flank'],
  },
  {
    id: 'Ambessa',
    name: 'Ambessa',
    role: 'Top',
    tags: ['Bruiser', 'Skirmisher'],
    stats: { range: 2, burst: 8, cc: 4, mobility: 7, waveclear: 7, scaling: 7 },
    synergies: ['Dive', 'Snowball'],
  },
  {
    id: 'Camille',
    name: 'Camille',
    role: 'Top',
    tags: ['Diver', 'Skirmisher'],
    stats: { range: 2, burst: 8, cc: 7, mobility: 8, waveclear: 6, scaling: 8 },
    synergies: ['Pick', 'Dive'],
  },
  {
    id: 'ChoGath',
    name: "Cho'Gath",
    role: 'Top',
    tags: ['Tank', 'Control'],
    stats: { range: 2, burst: 6, cc: 8, mobility: 2, waveclear: 7, scaling: 8 },
    synergies: ['CC_Chain', 'Frontline'],
  },
  {
    id: 'Darius',
    name: 'Darius',
    role: 'Top',
    tags: ['Juggernaut', 'Lane Bully'],
    stats: { range: 1, burst: 8, cc: 5, mobility: 3, waveclear: 6, scaling: 7 },
    synergies: ['Snowball', 'Frontline'],
  },
  {
    id: 'DrMundo',
    name: 'Dr. Mundo',
    role: 'Top',
    tags: ['Juggernaut', 'Tank'],
    stats: { range: 2, burst: 4, cc: 2, mobility: 4, waveclear: 6, scaling: 8 },
    synergies: ['Sustain', 'Frontline'],
  },
  {
    id: 'Fiora',
    name: 'Fiora',
    role: 'Top',
    tags: ['Skirmisher', 'Splitpush'],
    stats: { range: 1, burst: 7, cc: 3, mobility: 8, waveclear: 5, scaling: 9 },
    synergies: ['Split_Push', 'Duelist'],
  },
  {
    id: 'Gangplank',
    name: 'Gangplank',
    role: 'Top',
    tags: ['Scaling', 'Poke'],
    stats: { range: 2, burst: 9, cc: 4, mobility: 3, waveclear: 9, scaling: 10 },
    synergies: ['Aoe_Damage', 'Zone_Control'],
  },
  {
    id: 'Garen',
    name: 'Garen',
    role: 'Top',
    tags: ['Juggernaut', 'Bruiser'],
    stats: { range: 1, burst: 6, cc: 2, mobility: 5, waveclear: 7, scaling: 6 },
    synergies: ['Frontline', 'Anti_Carry'],
  },
  {
    id: 'Gnar',
    name: 'Gnar',
    role: 'Top',
    tags: ['Ranged', 'Teamfight'],
    stats: { range: 8, burst: 6, cc: 8, mobility: 6, waveclear: 7, scaling: 7 },
    synergies: ['Engage', 'Aoe_Damage'],
  },
  {
    id: 'Gwen',
    name: 'Gwen',
    role: 'Top',
    tags: ['Skirmisher', 'AP Carry'],
    stats: { range: 2, burst: 7, cc: 1, mobility: 7, waveclear: 7, scaling: 9 },
    synergies: ['Split_Push', 'Aoe_Damage'],
  },
  {
    id: 'Illaoi',
    name: 'Illaoi',
    role: 'Top',
    tags: ['Juggernaut', 'Zone Control'],
    stats: { range: 2, burst: 8, cc: 4, mobility: 2, waveclear: 8, scaling: 7 },
    synergies: ['Aoe_Damage', 'Frontline'],
  },
  {
    id: 'Irelia',
    name: 'Irelia',
    role: 'Top',
    tags: ['Skirmisher', 'Carry'],
    stats: { range: 2, burst: 8, cc: 5, mobility: 9, waveclear: 8, scaling: 8 },
    synergies: ['Dive', 'Snowball'],
  },
  {
    id: 'Jax',
    name: 'Jax',
    role: 'Top',
    tags: ['Skirmisher', 'Splitpush'],
    stats: { range: 1, burst: 7, cc: 5, mobility: 7, waveclear: 6, scaling: 10 },
    synergies: ['Split_Push', 'Duelist'],
  },
  {
    id: 'Jayce',
    name: 'Jayce',
    role: 'Top',
    tags: ['Poke', 'Lane Bully'],
    stats: { range: 9, burst: 8, cc: 2, mobility: 6, waveclear: 8, scaling: 6 },
    synergies: ['Poke_Siege', 'Snowball'],
  },
  {
    id: 'KSante',
    name: "K'Sante",
    role: 'Top',
    tags: ['Tank', 'Skirmisher'],
    stats: { range: 2, burst: 6, cc: 8, mobility: 6, waveclear: 6, scaling: 7 },
    synergies: ['CC_Chain', 'Frontline'],
  },
  {
    id: 'Kayle',
    name: 'Kayle',
    role: 'Top',
    tags: ['Scaling', 'Hybrid Carry'],
    stats: { range: 9, burst: 5, cc: 2, mobility: 3, waveclear: 7, scaling: 10 },
    synergies: ['Hypercarry', 'Protect_Carry'],
  },
  {
    id: 'Kennen',
    name: 'Kennen',
    role: 'Top',
    tags: ['Teamfight', 'AP Engage'],
    stats: { range: 8, burst: 8, cc: 8, mobility: 6, waveclear: 6, scaling: 7 },
    synergies: ['Engage', 'Aoe_Damage'],
  },
  {
    id: 'Kled',
    name: 'Kled',
    role: 'Top',
    tags: ['Diver', 'Skirmisher'],
    stats: { range: 2, burst: 7, cc: 6, mobility: 7, waveclear: 6, scaling: 6 },
    synergies: ['Dive', 'Snowball'],
  },
  {
    id: 'Malphite',
    name: 'Malphite',
    role: 'Top',
    tags: ['Tank', 'Engage'],
    stats: { range: 2, burst: 7, cc: 9, mobility: 5, waveclear: 6, scaling: 7 },
    synergies: ['CC_Chain', 'Aoe_Damage'],
  },
  {
    id: 'Maokai',
    name: 'Maokai',
    role: 'Top',
    tags: ['Tank', 'Control'],
    stats: { range: 2, burst: 4, cc: 9, mobility: 3, waveclear: 6, scaling: 7 },
    synergies: ['CC_Chain', 'Frontline'],
  },
  {
    id: 'Mordekaiser',
    name: 'Mordekaiser',
    role: 'Top',
    tags: ['Juggernaut', 'AP Bruiser'],
    stats: { range: 2, burst: 7, cc: 4, mobility: 3, waveclear: 7, scaling: 8 },
    synergies: ['Pick', 'Duelist'],
  },
  {
    id: 'Nasus',
    name: 'Nasus',
    role: 'Top',
    tags: ['Scaling', 'Juggernaut'],
    stats: { range: 1, burst: 5, cc: 5, mobility: 2, waveclear: 6, scaling: 9 },
    synergies: ['Split_Push', 'Frontline'],
  },
  {
    id: 'Olaf',
    name: 'Olaf',
    role: 'Top',
    tags: ['Bruiser', 'Skirmisher'],
    stats: { range: 1, burst: 7, cc: 2, mobility: 6, waveclear: 6, scaling: 6 },
    synergies: ['Dive', 'Snowball'],
  },
  {
    id: 'Ornn',
    name: 'Ornn',
    role: 'Top',
    tags: ['Tank', 'Engage'],
    stats: { range: 2, burst: 6, cc: 9, mobility: 3, waveclear: 7, scaling: 8 },
    synergies: ['Engage', 'Frontline'],
  },
  {
    id: 'Pantheon',
    name: 'Pantheon',
    role: 'Top',
    tags: ['Bruiser', 'Early Game'],
    stats: { range: 2, burst: 8, cc: 4, mobility: 5, waveclear: 5, scaling: 5 },
    synergies: ['Dive', 'Global_Pressure'],
  },
  {
    id: 'Poppy',
    name: 'Poppy',
    role: 'Top',
    tags: ['Tank', 'Anti-Dash'],
    stats: { range: 1, burst: 5, cc: 8, mobility: 3, waveclear: 5, scaling: 7 },
    synergies: ['Disengage', 'CC_Chain'],
  },
  {
    id: 'Quinn',
    name: 'Quinn',
    role: 'Top',
    tags: ['Ranged', 'Roam'],
    stats: { range: 8, burst: 7, cc: 3, mobility: 9, waveclear: 6, scaling: 6 },
    synergies: ['Split_Push', 'Global_Pressure'],
  },
  {
    id: 'Renekton',
    name: 'Renekton',
    role: 'Top',
    tags: ['Bruiser', 'Lane Bully'],
    stats: { range: 1, burst: 8, cc: 6, mobility: 6, waveclear: 7, scaling: 5 },
    synergies: ['Dive', 'Snowball'],
  },
  {
    id: 'Riven',
    name: 'Riven',
    role: 'Top',
    tags: ['Skirmisher', 'Carry'],
    stats: { range: 1, burst: 9, cc: 6, mobility: 9, waveclear: 7, scaling: 7 },
    synergies: ['Dive', 'Aoe_Damage'],
  },
  {
    id: 'Rumble',
    name: 'Rumble',
    role: 'Top',
    tags: ['AP Bruiser', 'Teamfight'],
    stats: { range: 3, burst: 8, cc: 4, mobility: 4, waveclear: 8, scaling: 7 },
    synergies: ['Aoe_Damage', 'Zone_Control'],
  },
  {
    id: 'Sejuani',
    name: 'Sejuani',
    role: 'Top',
    tags: ['Tank', 'Engage'],
    stats: { range: 1, burst: 4, cc: 9, mobility: 4, waveclear: 5, scaling: 7 },
    synergies: ['CC_Chain', 'Frontline'],
  },
  {
    id: 'Sett',
    name: 'Sett',
    role: 'Top',
    tags: ['Bruiser', 'Teamfight'],
    stats: { range: 1, burst: 7, cc: 7, mobility: 4, waveclear: 6, scaling: 7 },
    synergies: ['Engage', 'Aoe_Damage'],
  },
  {
    id: 'Shen',
    name: 'Shen',
    role: 'Top',
    tags: ['Tank', 'Global'],
    stats: { range: 1, burst: 4, cc: 7, mobility: 4, waveclear: 5, scaling: 7 },
    synergies: ['Global_Pressure', 'Protect_Carry'],
  },
  {
    id: 'Singed',
    name: 'Singed',
    role: 'Top',
    tags: ['Disruptor', 'AP Bruiser'],
    stats: { range: 1, burst: 5, cc: 6, mobility: 7, waveclear: 8, scaling: 6 },
    synergies: ['Disengage', 'Zone_Control'],
  },
  {
    id: 'Sion',
    name: 'Sion',
    role: 'Top',
    tags: ['Tank', 'Engage'],
    stats: { range: 2, burst: 6, cc: 8, mobility: 3, waveclear: 8, scaling: 8 },
    synergies: ['Engage', 'Frontline'],
  },
  {
    id: 'Teemo',
    name: 'Teemo',
    role: 'Top',
    tags: ['Ranged', 'Control'],
    stats: { range: 8, burst: 6, cc: 4, mobility: 5, waveclear: 6, scaling: 6 },
    synergies: ['Zone_Control', 'Split_Push'],
  },
  {
    id: 'Tryndamere',
    name: 'Tryndamere',
    role: 'Top',
    tags: ['Splitpush', 'Duelist'],
    stats: { range: 1, burst: 7, cc: 1, mobility: 7, waveclear: 7, scaling: 8 },
    synergies: ['Split_Push', 'Duelist'],
  },
  {
    id: 'Urgot',
    name: 'Urgot',
    role: 'Top',
    tags: ['Juggernaut', 'Ranged'],
    stats: { range: 6, burst: 7, cc: 5, mobility: 3, waveclear: 7, scaling: 7 },
    synergies: ['Frontline', 'Execute'],
  },
  {
    id: 'Vayne',
    name: 'Vayne',
    role: 'Top',
    tags: ['Marksman', 'Duelist'],
    stats: { range: 7, burst: 5, cc: 2, mobility: 8, waveclear: 3, scaling: 9 },
    synergies: ['Hypercarry', 'Split_Push'],
  },
  {
    id: 'Volibear',
    name: 'Volibear',
    role: 'Top',
    tags: ['Bruiser', 'Diver'],
    stats: { range: 1, burst: 7, cc: 6, mobility: 5, waveclear: 7, scaling: 6 },
    synergies: ['Dive', 'Frontline'],
  },
  {
    id: 'Warwick',
    name: 'Warwick',
    role: 'Top',
    tags: ['Bruiser', 'Sustain'],
    stats: { range: 1, burst: 6, cc: 5, mobility: 6, waveclear: 5, scaling: 6 },
    synergies: ['Pick', 'Sustain'],
  },
  {
    id: 'Wukong',
    name: 'Wukong',
    role: 'Top',
    tags: ['Bruiser', 'Teamfight'],
    stats: { range: 1, burst: 7, cc: 8, mobility: 7, waveclear: 6, scaling: 7 },
    synergies: ['Engage', 'Aoe_Damage'],
  },
  {
    id: 'Yasuo',
    name: 'Yasuo',
    role: 'Top',
    tags: ['Skirmisher', 'Carry'],
    stats: { range: 1, burst: 8, cc: 4, mobility: 9, waveclear: 8, scaling: 8 },
    synergies: ['Knockup_Combo', 'Duelist'],
  },
  {
    id: 'Yone',
    name: 'Yone',
    role: 'Top',
    tags: ['Skirmisher', 'Carry'],
    stats: { range: 2, burst: 9, cc: 5, mobility: 8, waveclear: 8, scaling: 9 },
    synergies: ['Dive', 'Aoe_Damage'],
  },
  {
    id: 'Yorick',
    name: 'Yorick',
    role: 'Top',
    tags: ['Splitpush', 'Juggernaut'],
    stats: { range: 1, burst: 6, cc: 4, mobility: 2, waveclear: 8, scaling: 8 },
    synergies: ['Split_Push', 'Siege'],
  },
  {
    id: 'Zac',
    name: 'Zac',
    role: 'Top',
    tags: ['Tank', 'Engage'],
    stats: { range: 2, burst: 5, cc: 9, mobility: 7, waveclear: 6, scaling: 7 },
    synergies: ['Engage', 'CC_Chain'],
  },
]

const JUNGLE_CHAMPIONS = [
  {
    id: 'Amumu',
    name: 'Amumu',
    role: 'Jungle',
    tags: ['Tank', 'Engage'],
    stats: { range: 1, burst: 5, cc: 9, mobility: 4, waveclear: 6, scaling: 7 },
    synergies: ['CC_Chain', 'Aoe_Damage'],
  },
  {
    id: 'BelVeth',
    name: "Bel'Veth",
    role: 'Jungle',
    tags: ['Skirmisher', 'Carry'],
    stats: { range: 2, burst: 7, cc: 3, mobility: 8, waveclear: 8, scaling: 9 },
    synergies: ['Snowball', 'Objective_Control'],
  },
  {
    id: 'Brand',
    name: 'Brand',
    role: 'Jungle',
    tags: ['AP', 'Aoe Damage'],
    stats: { range: 8, burst: 8, cc: 3, mobility: 2, waveclear: 9, scaling: 8 },
    synergies: ['Aoe_Damage', 'Objective_Control'],
  },
  {
    id: 'Briar',
    name: 'Briar',
    role: 'Jungle',
    tags: ['Diver', 'Bruiser'],
    stats: { range: 1, burst: 8, cc: 4, mobility: 8, waveclear: 7, scaling: 7 },
    synergies: ['Dive', 'Snowball'],
  },
  {
    id: 'Diana',
    name: 'Diana',
    role: 'Jungle',
    tags: ['AP', 'Diver'],
    stats: { range: 2, burst: 8, cc: 5, mobility: 7, waveclear: 7, scaling: 8 },
    synergies: ['Engage', 'Aoe_Damage'],
  },
  {
    id: 'Ekko',
    name: 'Ekko',
    role: 'Jungle',
    tags: ['AP', 'Assassin'],
    stats: { range: 2, burst: 8, cc: 4, mobility: 9, waveclear: 7, scaling: 8 },
    synergies: ['Dive', 'Pick'],
  },
  {
    id: 'Elise',
    name: 'Elise',
    role: 'Jungle',
    tags: ['AP', 'Early Game'],
    stats: { range: 7, burst: 8, cc: 6, mobility: 7, waveclear: 6, scaling: 4 },
    synergies: ['Dive', 'Snowball'],
  },
  {
    id: 'Evelynn',
    name: 'Evelynn',
    role: 'Jungle',
    tags: ['AP', 'Assassin'],
    stats: { range: 2, burst: 10, cc: 3, mobility: 8, waveclear: 6, scaling: 8 },
    synergies: ['Pick', 'Flank'],
  },
  {
    id: 'Fiddlesticks',
    name: 'Fiddlesticks',
    role: 'Jungle',
    tags: ['AP', 'Teamfight'],
    stats: { range: 8, burst: 9, cc: 7, mobility: 4, waveclear: 8, scaling: 8 },
    synergies: ['Aoe_Damage', 'Flank'],
  },
  {
    id: 'Gragas',
    name: 'Gragas',
    role: 'Jungle',
    tags: ['Tank', 'AP'],
    stats: { range: 3, burst: 7, cc: 8, mobility: 6, waveclear: 7, scaling: 7 },
    synergies: ['Engage', 'Disengage'],
  },
  {
    id: 'Hecarim',
    name: 'Hecarim',
    role: 'Jungle',
    tags: ['Diver', 'Bruiser'],
    stats: { range: 1, burst: 7, cc: 5, mobility: 9, waveclear: 8, scaling: 7 },
    synergies: ['Dive', 'Engage'],
  },
  {
    id: 'Ivern',
    name: 'Ivern',
    role: 'Jungle',
    tags: ['Enchanter', 'Control'],
    stats: { range: 8, burst: 3, cc: 6, mobility: 5, waveclear: 4, scaling: 7 },
    synergies: ['Protect_Carry', 'Objective_Control'],
  },
  {
    id: 'JarvanIV',
    name: 'Jarvan IV',
    role: 'Jungle',
    tags: ['Engage', 'Bruiser'],
    stats: { range: 2, burst: 7, cc: 7, mobility: 7, waveclear: 6, scaling: 6 },
    synergies: ['Engage', 'CC_Chain'],
  },
  {
    id: 'Karthus',
    name: 'Karthus',
    role: 'Jungle',
    tags: ['AP', 'Scaling'],
    stats: { range: 8, burst: 7, cc: 2, mobility: 1, waveclear: 9, scaling: 9 },
    synergies: ['Aoe_Damage', 'Global_Pressure'],
  },
  {
    id: 'Khazix',
    name: "Kha'Zix",
    role: 'Jungle',
    tags: ['Assassin', 'Pick'],
    stats: { range: 1, burst: 9, cc: 2, mobility: 8, waveclear: 6, scaling: 7 },
    synergies: ['Pick', 'Flank'],
  },
  {
    id: 'Kindred',
    name: 'Kindred',
    role: 'Jungle',
    tags: ['Marksman', 'Scaling'],
    stats: { range: 8, burst: 6, cc: 3, mobility: 8, waveclear: 6, scaling: 9 },
    synergies: ['Hypercarry', 'Objective_Control'],
  },
  {
    id: 'LeeSin',
    name: 'Lee Sin',
    role: 'Jungle',
    tags: ['Playmaker', 'Early Game'],
    stats: { range: 1, burst: 8, cc: 5, mobility: 9, waveclear: 6, scaling: 5 },
    synergies: ['Pick', 'Insec'],
  },
  {
    id: 'Lillia',
    name: 'Lillia',
    role: 'Jungle',
    tags: ['AP', 'Skirmisher'],
    stats: { range: 3, burst: 7, cc: 7, mobility: 8, waveclear: 8, scaling: 8 },
    synergies: ['Aoe_Damage', 'CC_Chain'],
  },
  {
    id: 'Maokai',
    name: 'Maokai',
    role: 'Jungle',
    tags: ['Tank', 'Control'],
    stats: { range: 2, burst: 4, cc: 9, mobility: 3, waveclear: 6, scaling: 7 },
    synergies: ['CC_Chain', 'Frontline'],
  },
  {
    id: 'MasterYi',
    name: 'Master Yi',
    role: 'Jungle',
    tags: ['Carry', 'Skirmisher'],
    stats: { range: 1, burst: 8, cc: 1, mobility: 9, waveclear: 7, scaling: 9 },
    synergies: ['Snowball', 'Cleanup'],
  },
  {
    id: 'Morgana',
    name: 'Morgana',
    role: 'Jungle',
    tags: ['AP', 'Control'],
    stats: { range: 8, burst: 6, cc: 8, mobility: 3, waveclear: 8, scaling: 7 },
    synergies: ['Pick', 'CC_Chain'],
  },
  {
    id: 'Nidalee',
    name: 'Nidalee',
    role: 'Jungle',
    tags: ['AP', 'Skirmisher'],
    stats: { range: 9, burst: 9, cc: 1, mobility: 9, waveclear: 6, scaling: 6 },
    synergies: ['Snowball', 'Pick'],
  },
  {
    id: 'Nocturne',
    name: 'Nocturne',
    role: 'Jungle',
    tags: ['Diver', 'Global'],
    stats: { range: 1, burst: 8, cc: 4, mobility: 8, waveclear: 7, scaling: 7 },
    synergies: ['Global_Pressure', 'Dive'],
  },
  {
    id: 'NunuWillump',
    name: 'Nunu & Willump',
    role: 'Jungle',
    tags: ['Tank', 'Gank'],
    stats: { range: 1, burst: 5, cc: 8, mobility: 7, waveclear: 7, scaling: 6 },
    synergies: ['Engage', 'Objective_Control'],
  },
  {
    id: 'Olaf',
    name: 'Olaf',
    role: 'Jungle',
    tags: ['Bruiser', 'Skirmisher'],
    stats: { range: 1, burst: 7, cc: 2, mobility: 6, waveclear: 7, scaling: 6 },
    synergies: ['Dive', 'Snowball'],
  },
  {
    id: 'Pantheon',
    name: 'Pantheon',
    role: 'Jungle',
    tags: ['Bruiser', 'Early Game'],
    stats: { range: 2, burst: 8, cc: 4, mobility: 6, waveclear: 5, scaling: 5 },
    synergies: ['Global_Pressure', 'Dive'],
  },
  {
    id: 'Poppy',
    name: 'Poppy',
    role: 'Jungle',
    tags: ['Tank', 'Control'],
    stats: { range: 1, burst: 5, cc: 8, mobility: 4, waveclear: 5, scaling: 7 },
    synergies: ['Disengage', 'CC_Chain'],
  },
  {
    id: 'Rammus',
    name: 'Rammus',
    role: 'Jungle',
    tags: ['Tank', 'Engage'],
    stats: { range: 1, burst: 5, cc: 8, mobility: 8, waveclear: 6, scaling: 6 },
    synergies: ['Engage', 'Anti_Carry'],
  },
  {
    id: 'RekSai',
    name: "Rek'Sai",
    role: 'Jungle',
    tags: ['Diver', 'Early Game'],
    stats: { range: 1, burst: 8, cc: 6, mobility: 8, waveclear: 6, scaling: 5 },
    synergies: ['Pick', 'Snowball'],
  },
  {
    id: 'Rengar',
    name: 'Rengar',
    role: 'Jungle',
    tags: ['Assassin', 'Skirmisher'],
    stats: { range: 1, burst: 10, cc: 3, mobility: 9, waveclear: 6, scaling: 7 },
    synergies: ['Pick', 'Flank'],
  },
  {
    id: 'Sejuani',
    name: 'Sejuani',
    role: 'Jungle',
    tags: ['Tank', 'Engage'],
    stats: { range: 1, burst: 4, cc: 9, mobility: 5, waveclear: 5, scaling: 7 },
    synergies: ['CC_Chain', 'Frontline'],
  },
  {
    id: 'Shaco',
    name: 'Shaco',
    role: 'Jungle',
    tags: ['Assassin', 'Trickster'],
    stats: { range: 2, burst: 9, cc: 3, mobility: 8, waveclear: 6, scaling: 6 },
    synergies: ['Pick', 'Mindgame'],
  },
  {
    id: 'Skarner',
    name: 'Skarner',
    role: 'Jungle',
    tags: ['Tank', 'Pick'],
    stats: { range: 1, burst: 5, cc: 9, mobility: 5, waveclear: 6, scaling: 7 },
    synergies: ['Pick', 'Frontline'],
  },
  {
    id: 'Taliyah',
    name: 'Taliyah',
    role: 'Jungle',
    tags: ['AP', 'Control'],
    stats: { range: 9, burst: 8, cc: 6, mobility: 5, waveclear: 8, scaling: 7 },
    synergies: ['Zone_Control', 'Pick'],
  },
  {
    id: 'Talon',
    name: 'Talon',
    role: 'Jungle',
    tags: ['Assassin', 'Roam'],
    stats: { range: 1, burst: 9, cc: 2, mobility: 9, waveclear: 8, scaling: 6 },
    synergies: ['Flank', 'Snowball'],
  },
  {
    id: 'Trundle',
    name: 'Trundle',
    role: 'Jungle',
    tags: ['Bruiser', 'Anti-Tank'],
    stats: { range: 1, burst: 6, cc: 4, mobility: 4, waveclear: 6, scaling: 7 },
    synergies: ['Frontline', 'Duelist'],
  },
  {
    id: 'Udyr',
    name: 'Udyr',
    role: 'Jungle',
    tags: ['Bruiser', 'Tempo'],
    stats: { range: 1, burst: 6, cc: 4, mobility: 7, waveclear: 9, scaling: 7 },
    synergies: ['Objective_Control', 'Frontline'],
  },
  {
    id: 'Vi',
    name: 'Vi',
    role: 'Jungle',
    tags: ['Diver', 'Pick'],
    stats: { range: 1, burst: 8, cc: 7, mobility: 7, waveclear: 7, scaling: 7 },
    synergies: ['Pick', 'Dive'],
  },
  {
    id: 'Viego',
    name: 'Viego',
    role: 'Jungle',
    tags: ['Skirmisher', 'Carry'],
    stats: { range: 2, burst: 8, cc: 3, mobility: 8, waveclear: 7, scaling: 8 },
    synergies: ['Cleanup', 'Snowball'],
  },
  {
    id: 'Volibear',
    name: 'Volibear',
    role: 'Jungle',
    tags: ['Bruiser', 'Diver'],
    stats: { range: 1, burst: 7, cc: 6, mobility: 6, waveclear: 7, scaling: 6 },
    synergies: ['Dive', 'Frontline'],
  },
  {
    id: 'Warwick',
    name: 'Warwick',
    role: 'Jungle',
    tags: ['Bruiser', 'Pick'],
    stats: { range: 1, burst: 6, cc: 6, mobility: 7, waveclear: 6, scaling: 6 },
    synergies: ['Pick', 'Sustain'],
  },
  {
    id: 'Wukong',
    name: 'Wukong',
    role: 'Jungle',
    tags: ['Bruiser', 'Teamfight'],
    stats: { range: 1, burst: 7, cc: 8, mobility: 7, waveclear: 6, scaling: 7 },
    synergies: ['Engage', 'Aoe_Damage'],
  },
  {
    id: 'XinZhao',
    name: 'Xin Zhao',
    role: 'Jungle',
    tags: ['Bruiser', 'Diver'],
    stats: { range: 2, burst: 7, cc: 6, mobility: 7, waveclear: 6, scaling: 6 },
    synergies: ['Dive', 'Frontline'],
  },
  {
    id: 'Zaahen',
    name: 'Zaahen',
    role: 'Jungle',
    tags: ['Assassin', 'Skirmisher'],
    stats: { range: 1, burst: 9, cc: 3, mobility: 8, waveclear: 7, scaling: 7 },
    synergies: ['Pick', 'Flank'],
  },
  {
    id: 'Zac',
    name: 'Zac',
    role: 'Jungle',
    tags: ['Tank', 'Engage'],
    stats: { range: 2, burst: 5, cc: 9, mobility: 7, waveclear: 6, scaling: 7 },
    synergies: ['Engage', 'CC_Chain'],
  },
  {
    id: 'Zyra',
    name: 'Zyra',
    role: 'Jungle',
    tags: ['AP', 'Control'],
    stats: { range: 9, burst: 7, cc: 6, mobility: 2, waveclear: 8, scaling: 7 },
    synergies: ['Zone_Control', 'Pick'],
  },
]

const JUNGLE_PATHING_STATS = {
  Amumu: { ClearSpeed: 7, GankPressure: 7, ObjectiveControl: 7 },
  BelVeth: { ClearSpeed: 9, GankPressure: 6, ObjectiveControl: 9 },
  Brand: { ClearSpeed: 10, GankPressure: 5, ObjectiveControl: 8 },
  Briar: { ClearSpeed: 8, GankPressure: 8, ObjectiveControl: 7 },
  Diana: { ClearSpeed: 8, GankPressure: 6, ObjectiveControl: 8 },
  Ekko: { ClearSpeed: 7, GankPressure: 7, ObjectiveControl: 6 },
  Elise: { ClearSpeed: 6, GankPressure: 9, ObjectiveControl: 6 },
  Evelynn: { ClearSpeed: 7, GankPressure: 8, ObjectiveControl: 6 },
  Fiddlesticks: { ClearSpeed: 9, GankPressure: 7, ObjectiveControl: 7 },
  Gragas: { ClearSpeed: 7, GankPressure: 8, ObjectiveControl: 7 },
  Hecarim: { ClearSpeed: 9, GankPressure: 8, ObjectiveControl: 8 },
  Ivern: { ClearSpeed: 6, GankPressure: 6, ObjectiveControl: 7 },
  JarvanIV: { ClearSpeed: 7, GankPressure: 9, ObjectiveControl: 8 },
  Karthus: { ClearSpeed: 10, GankPressure: 4, ObjectiveControl: 9 },
  Khazix: { ClearSpeed: 7, GankPressure: 8, ObjectiveControl: 6 },
  Kindred: { ClearSpeed: 7, GankPressure: 6, ObjectiveControl: 8 },
  LeeSin: { ClearSpeed: 6, GankPressure: 10, ObjectiveControl: 7 },
  Lillia: { ClearSpeed: 9, GankPressure: 6, ObjectiveControl: 8 },
  Maokai: { ClearSpeed: 6, GankPressure: 8, ObjectiveControl: 7 },
  MasterYi: { ClearSpeed: 8, GankPressure: 5, ObjectiveControl: 8 },
  Morgana: { ClearSpeed: 9, GankPressure: 5, ObjectiveControl: 7 },
  Nidalee: { ClearSpeed: 8, GankPressure: 8, ObjectiveControl: 7 },
  Nocturne: { ClearSpeed: 8, GankPressure: 8, ObjectiveControl: 7 },
  NunuWillump: { ClearSpeed: 8, GankPressure: 9, ObjectiveControl: 9 },
  Olaf: { ClearSpeed: 8, GankPressure: 7, ObjectiveControl: 8 },
  Pantheon: { ClearSpeed: 6, GankPressure: 8, ObjectiveControl: 6 },
  Poppy: { ClearSpeed: 6, GankPressure: 7, ObjectiveControl: 7 },
  Rammus: { ClearSpeed: 7, GankPressure: 8, ObjectiveControl: 6 },
  RekSai: { ClearSpeed: 7, GankPressure: 9, ObjectiveControl: 7 },
  Rengar: { ClearSpeed: 7, GankPressure: 9, ObjectiveControl: 7 },
  Sejuani: { ClearSpeed: 6, GankPressure: 8, ObjectiveControl: 8 },
  Shaco: { ClearSpeed: 7, GankPressure: 8, ObjectiveControl: 6 },
  Skarner: { ClearSpeed: 7, GankPressure: 8, ObjectiveControl: 8 },
  Taliyah: { ClearSpeed: 8, GankPressure: 7, ObjectiveControl: 8 },
  Talon: { ClearSpeed: 8, GankPressure: 8, ObjectiveControl: 7 },
  Trundle: { ClearSpeed: 7, GankPressure: 6, ObjectiveControl: 8 },
  Udyr: { ClearSpeed: 10, GankPressure: 6, ObjectiveControl: 9 },
  Vi: { ClearSpeed: 7, GankPressure: 9, ObjectiveControl: 8 },
  Viego: { ClearSpeed: 8, GankPressure: 7, ObjectiveControl: 8 },
  Volibear: { ClearSpeed: 8, GankPressure: 8, ObjectiveControl: 8 },
  Warwick: { ClearSpeed: 7, GankPressure: 8, ObjectiveControl: 7 },
  Wukong: { ClearSpeed: 7, GankPressure: 7, ObjectiveControl: 7 },
  XinZhao: { ClearSpeed: 7, GankPressure: 8, ObjectiveControl: 7 },
  Zaahen: { ClearSpeed: 8, GankPressure: 8, ObjectiveControl: 7 },
  Zac: { ClearSpeed: 7, GankPressure: 9, ObjectiveControl: 7 },
  Zyra: { ClearSpeed: 8, GankPressure: 6, ObjectiveControl: 7 },
}

const JUNGLE_CHAMPIONS_WITH_PATHING = JUNGLE_CHAMPIONS.map((champion) => ({
  ...champion,
  jungleStats: JUNGLE_PATHING_STATS[champion.id] ?? {
    ClearSpeed: 5,
    GankPressure: 5,
    ObjectiveControl: 5,
  },
}))

const MIDLANE_CHAMPIONS = [
  {
    id: 'Ahri',
    name: 'Ahri',
    role: 'Mid',
    tags: ['Mage', 'Pick'],
    stats: { range: 8, burst: 8, cc: 6, mobility: 8, waveclear: 7, scaling: 7 },
    synergies: ['Pick', 'Flank'],
  },
  {
    id: 'Akali',
    name: 'Akali',
    role: 'Mid',
    tags: ['Assassin', 'Skirmisher'],
    stats: { range: 1, burst: 9, cc: 2, mobility: 9, waveclear: 6, scaling: 7 },
    synergies: ['Dive', 'Flank'],
  },
  {
    id: 'Akshan',
    name: 'Akshan',
    role: 'Mid',
    tags: ['Marksman', 'Assassin'],
    stats: { range: 8, burst: 8, cc: 2, mobility: 8, waveclear: 7, scaling: 7 },
    synergies: ['Skirmish', 'Flank'],
  },
  {
    id: 'Anivia',
    name: 'Anivia',
    role: 'Mid',
    tags: ['Control Mage', 'Scaling'],
    stats: { range: 8, burst: 7, cc: 8, mobility: 1, waveclear: 9, scaling: 9 },
    synergies: ['Zone_Control', 'Siege'],
  },
  {
    id: 'Annie',
    name: 'Annie',
    role: 'Mid',
    tags: ['Burst Mage', 'Engage'],
    stats: { range: 7, burst: 9, cc: 8, mobility: 2, waveclear: 6, scaling: 7 },
    synergies: ['Pick', 'Aoe_Damage'],
  },
  {
    id: 'AurelionSol',
    name: 'Aurelion Sol',
    role: 'Mid',
    tags: ['Scaling', 'Control Mage'],
    stats: { range: 9, burst: 6, cc: 7, mobility: 3, waveclear: 9, scaling: 10 },
    synergies: ['Zone_Control', 'Siege'],
  },
  {
    id: 'Aurora',
    name: 'Aurora',
    role: 'Mid',
    tags: ['Burst Mage', 'Skirmisher'],
    stats: { range: 8, burst: 8, cc: 6, mobility: 7, waveclear: 7, scaling: 8 },
    synergies: ['Pick', 'Skirmish'],
  },
  {
    id: 'Azir',
    name: 'Azir',
    role: 'Mid',
    tags: ['Control Mage', 'DPS'],
    stats: { range: 9, burst: 7, cc: 5, mobility: 5, waveclear: 8, scaling: 10 },
    synergies: ['Siege', 'Protect_Carry'],
  },
  {
    id: 'Brand',
    name: 'Brand',
    role: 'Mid',
    tags: ['Burst Mage', 'Aoe'],
    stats: { range: 8, burst: 8, cc: 3, mobility: 1, waveclear: 8, scaling: 7 },
    synergies: ['Aoe_Damage', 'Zone_Control'],
  },
  {
    id: 'Cassiopeia',
    name: 'Cassiopeia',
    role: 'Mid',
    tags: ['DPS Mage', 'Scaling'],
    stats: { range: 8, burst: 6, cc: 7, mobility: 2, waveclear: 8, scaling: 9 },
    synergies: ['Zone_Control', 'Front_to_Back'],
  },
  {
    id: 'Corki',
    name: 'Corki',
    role: 'Mid',
    tags: ['Poke', 'Scaling'],
    stats: { range: 8, burst: 8, cc: 2, mobility: 5, waveclear: 8, scaling: 9 },
    synergies: ['Poke_Siege', 'Objective_Control'],
  },
  {
    id: 'Diana',
    name: 'Diana',
    role: 'Mid',
    tags: ['AP', 'Diver'],
    stats: { range: 2, burst: 8, cc: 5, mobility: 7, waveclear: 7, scaling: 8 },
    synergies: ['Dive', 'Aoe_Damage'],
  },
  {
    id: 'Ekko',
    name: 'Ekko',
    role: 'Mid',
    tags: ['AP', 'Assassin'],
    stats: { range: 2, burst: 8, cc: 4, mobility: 9, waveclear: 7, scaling: 8 },
    synergies: ['Flank', 'Pick'],
  },
  {
    id: 'Fizz',
    name: 'Fizz',
    role: 'Mid',
    tags: ['Assassin', 'Skirmisher'],
    stats: { range: 1, burst: 10, cc: 3, mobility: 9, waveclear: 5, scaling: 7 },
    synergies: ['Pick', 'Dive'],
  },
  {
    id: 'Galio',
    name: 'Galio',
    role: 'Mid',
    tags: ['Tank Mage', 'Global'],
    stats: { range: 6, burst: 6, cc: 8, mobility: 5, waveclear: 7, scaling: 7 },
    synergies: ['Global_Pressure', 'Engage'],
  },
  {
    id: 'Hwei',
    name: 'Hwei',
    role: 'Mid',
    tags: ['Control Mage', 'Utility'],
    stats: { range: 9, burst: 7, cc: 7, mobility: 2, waveclear: 8, scaling: 8 },
    synergies: ['Zone_Control', 'Aoe_Damage'],
  },
  {
    id: 'Irelia',
    name: 'Irelia',
    role: 'Mid',
    tags: ['Skirmisher', 'Carry'],
    stats: { range: 2, burst: 8, cc: 5, mobility: 9, waveclear: 8, scaling: 8 },
    synergies: ['Dive', 'Snowball'],
  },
  {
    id: 'Jayce',
    name: 'Jayce',
    role: 'Mid',
    tags: ['Poke', 'Lane Bully'],
    stats: { range: 9, burst: 8, cc: 2, mobility: 6, waveclear: 8, scaling: 6 },
    synergies: ['Poke_Siege', 'Snowball'],
  },
  {
    id: 'Kassadin',
    name: 'Kassadin',
    role: 'Mid',
    tags: ['Assassin', 'Scaling'],
    stats: { range: 2, burst: 9, cc: 2, mobility: 10, waveclear: 6, scaling: 10 },
    synergies: ['Flank', 'Hypercarry'],
  },
  {
    id: 'Katarina',
    name: 'Katarina',
    role: 'Mid',
    tags: ['Assassin', 'Reset'],
    stats: { range: 1, burst: 9, cc: 1, mobility: 10, waveclear: 7, scaling: 8 },
    synergies: ['Cleanup', 'Dive'],
  },
  {
    id: 'LeBlanc',
    name: 'LeBlanc',
    role: 'Mid',
    tags: ['Assassin', 'Pick'],
    stats: { range: 8, burst: 10, cc: 4, mobility: 10, waveclear: 5, scaling: 6 },
    synergies: ['Pick', 'Flank'],
  },
  {
    id: 'Lissandra',
    name: 'Lissandra',
    role: 'Mid',
    tags: ['Control Mage', 'Engage'],
    stats: { range: 7, burst: 7, cc: 9, mobility: 4, waveclear: 7, scaling: 7 },
    synergies: ['CC_Chain', 'Engage'],
  },
  {
    id: 'Lucian',
    name: 'Lucian',
    role: 'Mid',
    tags: ['Marksman', 'Lane Bully'],
    stats: { range: 7, burst: 8, cc: 1, mobility: 8, waveclear: 7, scaling: 6 },
    synergies: ['Snowball', 'Skirmish'],
  },
  {
    id: 'Lux',
    name: 'Lux',
    role: 'Mid',
    tags: ['Mage', 'Pick'],
    stats: { range: 10, burst: 8, cc: 8, mobility: 2, waveclear: 8, scaling: 7 },
    synergies: ['Pick', 'Poke_Siege'],
  },
  {
    id: 'Malzahar',
    name: 'Malzahar',
    role: 'Mid',
    tags: ['Control Mage', 'Utility'],
    stats: { range: 8, burst: 6, cc: 9, mobility: 1, waveclear: 8, scaling: 7 },
    synergies: ['Pick', 'Front_to_Back'],
  },
  {
    id: 'Mel',
    name: 'Mel',
    role: 'Mid',
    tags: ['Control Mage', 'Utility'],
    stats: { range: 8, burst: 7, cc: 7, mobility: 3, waveclear: 7, scaling: 8 },
    synergies: ['Zone_Control', 'Protect_Carry'],
  },
  {
    id: 'Naafiri',
    name: 'Naafiri',
    role: 'Mid',
    tags: ['Assassin', 'Roam'],
    stats: { range: 1, burst: 9, cc: 2, mobility: 8, waveclear: 6, scaling: 7 },
    synergies: ['Flank', 'Pick'],
  },
  {
    id: 'Neeko',
    name: 'Neeko',
    role: 'Mid',
    tags: ['Mage', 'Engage'],
    stats: { range: 8, burst: 8, cc: 8, mobility: 4, waveclear: 7, scaling: 7 },
    synergies: ['Engage', 'Aoe_Damage'],
  },
  {
    id: 'Orianna',
    name: 'Orianna',
    role: 'Mid',
    tags: ['Control Mage', 'Teamfight'],
    stats: { range: 8, burst: 7, cc: 8, mobility: 2, waveclear: 8, scaling: 9 },
    synergies: ['Aoe_Damage', 'Front_to_Back'],
  },
  {
    id: 'Qiyana',
    name: 'Qiyana',
    role: 'Mid',
    tags: ['Assassin', 'Roam'],
    stats: { range: 1, burst: 10, cc: 7, mobility: 8, waveclear: 7, scaling: 6 },
    synergies: ['Flank', 'Aoe_Damage'],
  },
  {
    id: 'Ryze',
    name: 'Ryze',
    role: 'Mid',
    tags: ['Battle Mage', 'Scaling'],
    stats: { range: 7, burst: 6, cc: 5, mobility: 4, waveclear: 8, scaling: 9 },
    synergies: ['Split_Push', 'Global_Pressure'],
  },
  {
    id: 'Smolder',
    name: 'Smolder',
    role: 'Mid',
    tags: ['Marksman', 'Scaling'],
    stats: { range: 8, burst: 5, cc: 1, mobility: 4, waveclear: 7, scaling: 10 },
    synergies: ['Hypercarry', 'Poke_Siege'],
  },
  {
    id: 'Sylas',
    name: 'Sylas',
    role: 'Mid',
    tags: ['AP Bruiser', 'Skirmisher'],
    stats: { range: 2, burst: 8, cc: 6, mobility: 8, waveclear: 6, scaling: 8 },
    synergies: ['Skirmish', 'Dive'],
  },
  {
    id: 'Syndra',
    name: 'Syndra',
    role: 'Mid',
    tags: ['Burst Mage', 'Control'],
    stats: { range: 9, burst: 9, cc: 6, mobility: 2, waveclear: 8, scaling: 8 },
    synergies: ['Pick', 'Poke_Siege'],
  },
  {
    id: 'Taliyah',
    name: 'Taliyah',
    role: 'Mid',
    tags: ['Control Mage', 'Roam'],
    stats: { range: 9, burst: 8, cc: 6, mobility: 5, waveclear: 8, scaling: 7 },
    synergies: ['Zone_Control', 'Global_Pressure'],
  },
  {
    id: 'Talon',
    name: 'Talon',
    role: 'Mid',
    tags: ['Assassin', 'Roam'],
    stats: { range: 1, burst: 9, cc: 2, mobility: 9, waveclear: 8, scaling: 6 },
    synergies: ['Flank', 'Snowball'],
  },
  {
    id: 'Tristana',
    name: 'Tristana',
    role: 'Mid',
    tags: ['Marksman', 'Siege'],
    stats: { range: 9, burst: 8, cc: 2, mobility: 7, waveclear: 8, scaling: 9 },
    synergies: ['Poke_Siege', 'Snowball'],
  },
  {
    id: 'TwistedFate',
    name: 'Twisted Fate',
    role: 'Mid',
    tags: ['Utility', 'Global'],
    stats: { range: 8, burst: 6, cc: 7, mobility: 4, waveclear: 7, scaling: 7 },
    synergies: ['Global_Pressure', 'Pick'],
  },
  {
    id: 'Veigar',
    name: 'Veigar',
    role: 'Mid',
    tags: ['Burst Mage', 'Scaling'],
    stats: { range: 8, burst: 10, cc: 9, mobility: 1, waveclear: 7, scaling: 10 },
    synergies: ['Zone_Control', 'Pick'],
  },
  {
    id: 'VelKoz',
    name: "Vel'Koz",
    role: 'Mid',
    tags: ['Artillery', 'Poke'],
    stats: { range: 10, burst: 8, cc: 6, mobility: 1, waveclear: 9, scaling: 8 },
    synergies: ['Poke_Siege', 'Aoe_Damage'],
  },
  {
    id: 'Vex',
    name: 'Vex',
    role: 'Mid',
    tags: ['Burst Mage', 'Anti-Mobility'],
    stats: { range: 8, burst: 8, cc: 7, mobility: 4, waveclear: 7, scaling: 7 },
    synergies: ['Pick', 'Dive'],
  },
  {
    id: 'Viktor',
    name: 'Viktor',
    role: 'Mid',
    tags: ['Control Mage', 'Scaling'],
    stats: { range: 9, burst: 7, cc: 5, mobility: 2, waveclear: 9, scaling: 9 },
    synergies: ['Zone_Control', 'Front_to_Back'],
  },
  {
    id: 'Vladimir',
    name: 'Vladimir',
    role: 'Mid',
    tags: ['Battle Mage', 'Scaling'],
    stats: { range: 6, burst: 8, cc: 2, mobility: 4, waveclear: 6, scaling: 9 },
    synergies: ['Aoe_Damage', 'Flank'],
  },
  {
    id: 'Xerath',
    name: 'Xerath',
    role: 'Mid',
    tags: ['Artillery', 'Poke'],
    stats: { range: 10, burst: 8, cc: 5, mobility: 1, waveclear: 9, scaling: 8 },
    synergies: ['Poke_Siege', 'Zone_Control'],
  },
  {
    id: 'Yasuo',
    name: 'Yasuo',
    role: 'Mid',
    tags: ['Skirmisher', 'Carry'],
    stats: { range: 1, burst: 8, cc: 4, mobility: 9, waveclear: 8, scaling: 8 },
    synergies: ['Knockup_Combo', 'Duelist'],
  },
  {
    id: 'Yone',
    name: 'Yone',
    role: 'Mid',
    tags: ['Skirmisher', 'Carry'],
    stats: { range: 2, burst: 9, cc: 5, mobility: 8, waveclear: 8, scaling: 9 },
    synergies: ['Dive', 'Aoe_Damage'],
  },
  {
    id: 'Zed',
    name: 'Zed',
    role: 'Mid',
    tags: ['Assassin', 'Skirmisher'],
    stats: { range: 4, burst: 10, cc: 2, mobility: 9, waveclear: 8, scaling: 7 },
    synergies: ['Pick', 'Flank'],
  },
  {
    id: 'Zoe',
    name: 'Zoe',
    role: 'Mid',
    tags: ['Burst Mage', 'Pick'],
    stats: { range: 10, burst: 10, cc: 7, mobility: 4, waveclear: 6, scaling: 7 },
    synergies: ['Pick', 'Poke_Siege'],
  },
]

const MIDLANE_MACRO_STATS = {
  Ahri: { RoamPotential: 8, LanePriority: 7, ManaManagement: 7 },
  Akali: { RoamPotential: 8, LanePriority: 7, EnergyManagement: 8 },
  Akshan: { RoamPotential: 8, LanePriority: 8, ManaManagement: 7 },
  Anivia: { RoamPotential: 3, LanePriority: 6, ManaManagement: 8 },
  Annie: { RoamPotential: 6, LanePriority: 6, ManaManagement: 7 },
  AurelionSol: { RoamPotential: 6, LanePriority: 7, ManaManagement: 6 },
  Aurora: { RoamPotential: 7, LanePriority: 7, ManaManagement: 6 },
  Azir: { RoamPotential: 4, LanePriority: 7, ManaManagement: 6 },
  Brand: { RoamPotential: 4, LanePriority: 7, ManaManagement: 6 },
  Cassiopeia: { RoamPotential: 3, LanePriority: 7, ManaManagement: 5 },
  Corki: { RoamPotential: 5, LanePriority: 7, ManaManagement: 7 },
  Diana: { RoamPotential: 7, LanePriority: 7, ManaManagement: 6 },
  Ekko: { RoamPotential: 8, LanePriority: 7, ManaManagement: 6 },
  Fizz: { RoamPotential: 8, LanePriority: 7, ManaManagement: 7 },
  Galio: { RoamPotential: 9, LanePriority: 7, ManaManagement: 8 },
  Hwei: { RoamPotential: 4, LanePriority: 6, ManaManagement: 5 },
  Irelia: { RoamPotential: 8, LanePriority: 8, ManaManagement: 7 },
  Jayce: { RoamPotential: 7, LanePriority: 8, ManaManagement: 8 },
  Kassadin: { RoamPotential: 7, LanePriority: 4, ManaManagement: 6 },
  Katarina: { RoamPotential: 8, LanePriority: 6, ManaManagement: 10 },
  LeBlanc: { RoamPotential: 9, LanePriority: 8, ManaManagement: 7 },
  Lissandra: { RoamPotential: 7, LanePriority: 7, ManaManagement: 7 },
  Lucian: { RoamPotential: 7, LanePriority: 8, ManaManagement: 6 },
  Lux: { RoamPotential: 4, LanePriority: 6, ManaManagement: 7 },
  Malzahar: { RoamPotential: 4, LanePriority: 7, ManaManagement: 8 },
  Mel: { RoamPotential: 6, LanePriority: 7, ManaManagement: 7 },
  Naafiri: { RoamPotential: 8, LanePriority: 7, ManaManagement: 7 },
  Neeko: { RoamPotential: 7, LanePriority: 7, ManaManagement: 7 },
  Orianna: { RoamPotential: 4, LanePriority: 8, ManaManagement: 7 },
  Qiyana: { RoamPotential: 9, LanePriority: 8, ManaManagement: 6 },
  Ryze: { RoamPotential: 6, LanePriority: 7, ManaManagement: 5 },
  Smolder: { RoamPotential: 4, LanePriority: 6, ManaManagement: 7 },
  Sylas: { RoamPotential: 8, LanePriority: 7, ManaManagement: 6 },
  Syndra: { RoamPotential: 5, LanePriority: 8, ManaManagement: 7 },
  Taliyah: { RoamPotential: 8, LanePriority: 8, ManaManagement: 6 },
  Talon: { RoamPotential: 9, LanePriority: 8, ManaManagement: 6 },
  Tristana: { RoamPotential: 7, LanePriority: 8, ManaManagement: 7 },
  TwistedFate: { RoamPotential: 10, LanePriority: 6, ManaManagement: 6 },
  Veigar: { RoamPotential: 3, LanePriority: 5, ManaManagement: 7 },
  VelKoz: { RoamPotential: 3, LanePriority: 7, ManaManagement: 7 },
  Vex: { RoamPotential: 6, LanePriority: 7, ManaManagement: 7 },
  Viktor: { RoamPotential: 3, LanePriority: 8, ManaManagement: 6 },
  Vladimir: { RoamPotential: 5, LanePriority: 6, ManaManagement: 10 },
  Xerath: { RoamPotential: 3, LanePriority: 7, ManaManagement: 8 },
  Yasuo: { RoamPotential: 8, LanePriority: 8, ManaManagement: 10 },
  Yone: { RoamPotential: 7, LanePriority: 8, ManaManagement: 10 },
  Zed: { RoamPotential: 9, LanePriority: 8, EnergyManagement: 8 },
  Zoe: { RoamPotential: 8, LanePriority: 8, ManaManagement: 6 },
}

const MIDLANE_CHAMPIONS_WITH_MACRO = MIDLANE_CHAMPIONS.map((champion) => {
  const stats = MIDLANE_MACRO_STATS[champion.id] ?? {
    RoamPotential: 5,
    LanePriority: 5,
    ManaManagement: 5,
  }

  return {
    ...champion,
    midlaneStats: {
      RoamPotential: stats.RoamPotential ?? 5,
      LanePriority: stats.LanePriority ?? 5,
      ManaManagement: stats.ManaManagement ?? 0,
      EnergyManagement: stats.EnergyManagement ?? 0,
    },
  }
})

const ADC_CHAMPIONS = [
  {
    id: 'Aphelios',
    name: 'Aphelios',
    role: 'ADC',
    tags: ['Marksman', 'Scaling'],
    stats: { range: 8, burst: 7, cc: 3, mobility: 2, waveclear: 7, scaling: 10 },
    synergies: ['Hypercarry', 'Front_to_Back'],
  },
  {
    id: 'Ashe',
    name: 'Ashe',
    role: 'ADC',
    tags: ['Marksman', 'Utility'],
    stats: { range: 8, burst: 5, cc: 8, mobility: 2, waveclear: 7, scaling: 7 },
    synergies: ['Pick', 'Front_to_Back'],
  },
  {
    id: 'Brand',
    name: 'Brand',
    role: 'ADC',
    tags: ['Mage', 'Aoe Damage'],
    stats: { range: 8, burst: 8, cc: 3, mobility: 1, waveclear: 8, scaling: 7 },
    synergies: ['Aoe_Damage', 'Zone_Control'],
  },
  {
    id: 'Caitlyn',
    name: 'Caitlyn',
    role: 'ADC',
    tags: ['Marksman', 'Lane Bully'],
    stats: { range: 10, burst: 7, cc: 4, mobility: 3, waveclear: 7, scaling: 8 },
    synergies: ['Poke_Siege', 'Objective_Control'],
  },
  {
    id: 'Cassiopeia',
    name: 'Cassiopeia',
    role: 'ADC',
    tags: ['DPS Mage', 'Scaling'],
    stats: { range: 8, burst: 6, cc: 7, mobility: 2, waveclear: 8, scaling: 9 },
    synergies: ['Front_to_Back', 'Zone_Control'],
  },
  {
    id: 'Corki',
    name: 'Corki',
    role: 'ADC',
    tags: ['Marksman', 'Poke'],
    stats: { range: 8, burst: 8, cc: 2, mobility: 5, waveclear: 8, scaling: 9 },
    synergies: ['Poke_Siege', 'Objective_Control'],
  },
  {
    id: 'Draven',
    name: 'Draven',
    role: 'ADC',
    tags: ['Marksman', 'Snowball'],
    stats: { range: 7, burst: 9, cc: 2, mobility: 4, waveclear: 6, scaling: 7 },
    synergies: ['Snowball', 'Lane_Dominance'],
  },
  {
    id: 'Ezreal',
    name: 'Ezreal',
    role: 'ADC',
    tags: ['Marksman', 'Poke'],
    stats: { range: 9, burst: 7, cc: 2, mobility: 8, waveclear: 6, scaling: 8 },
    synergies: ['Poke_Siege', 'Safe_Scaling'],
  },
  {
    id: 'Jhin',
    name: 'Jhin',
    role: 'ADC',
    tags: ['Marksman', 'Utility'],
    stats: { range: 9, burst: 9, cc: 6, mobility: 2, waveclear: 6, scaling: 7 },
    synergies: ['Pick', 'Front_to_Back'],
  },
  {
    id: 'Jinx',
    name: 'Jinx',
    role: 'ADC',
    tags: ['Marksman', 'Hypercarry'],
    stats: { range: 9, burst: 7, cc: 3, mobility: 3, waveclear: 8, scaling: 10 },
    synergies: ['Hypercarry', 'Front_to_Back'],
  },
  {
    id: 'KaiSa',
    name: "Kai'Sa",
    role: 'ADC',
    tags: ['Marksman', 'Diver'],
    stats: { range: 7, burst: 8, cc: 2, mobility: 8, waveclear: 7, scaling: 9 },
    synergies: ['Dive', 'Cleanup'],
  },
  {
    id: 'Kalista',
    name: 'Kalista',
    role: 'ADC',
    tags: ['Marksman', 'Skirmisher'],
    stats: { range: 7, burst: 6, cc: 5, mobility: 9, waveclear: 6, scaling: 7 },
    synergies: ['Skirmish', 'Objective_Control'],
  },
  {
    id: 'Karthus',
    name: 'Karthus',
    role: 'ADC',
    tags: ['Mage', 'Scaling'],
    stats: { range: 8, burst: 7, cc: 2, mobility: 1, waveclear: 9, scaling: 9 },
    synergies: ['Aoe_Damage', 'Global_Pressure'],
  },
  {
    id: 'KogMaw',
    name: "Kog'Maw",
    role: 'ADC',
    tags: ['Marksman', 'Hypercarry'],
    stats: { range: 10, burst: 6, cc: 2, mobility: 1, waveclear: 6, scaling: 10 },
    synergies: ['Hypercarry', 'Protect_Carry'],
  },
  {
    id: 'Lucian',
    name: 'Lucian',
    role: 'ADC',
    tags: ['Marksman', 'Lane Bully'],
    stats: { range: 7, burst: 8, cc: 1, mobility: 8, waveclear: 7, scaling: 6 },
    synergies: ['Snowball', 'Skirmish'],
  },
  {
    id: 'MissFortune',
    name: 'Miss Fortune',
    role: 'ADC',
    tags: ['Marksman', 'Teamfight'],
    stats: { range: 8, burst: 8, cc: 2, mobility: 4, waveclear: 7, scaling: 7 },
    synergies: ['Aoe_Damage', 'Teamfight_Ult'],
  },
  {
    id: 'Nilah',
    name: 'Nilah',
    role: 'ADC',
    tags: ['Skirmisher', 'Melee Carry'],
    stats: { range: 1, burst: 8, cc: 5, mobility: 8, waveclear: 6, scaling: 8 },
    synergies: ['Dive', 'Aoe_Damage'],
  },
  {
    id: 'Samira',
    name: 'Samira',
    role: 'ADC',
    tags: ['Marksman', 'Diver'],
    stats: { range: 6, burst: 9, cc: 3, mobility: 8, waveclear: 6, scaling: 8 },
    synergies: ['Dive', 'Cleanup'],
  },
  {
    id: 'Senna',
    name: 'Senna',
    role: 'ADC',
    tags: ['Marksman', 'Utility'],
    stats: { range: 10, burst: 6, cc: 6, mobility: 3, waveclear: 5, scaling: 8 },
    synergies: ['Pick', 'Poke_Siege'],
  },
  {
    id: 'Seraphine',
    name: 'Seraphine',
    role: 'ADC',
    tags: ['Mage', 'Utility'],
    stats: { range: 9, burst: 6, cc: 7, mobility: 2, waveclear: 8, scaling: 8 },
    synergies: ['Aoe_Damage', 'Front_to_Back'],
  },
  {
    id: 'Sivir',
    name: 'Sivir',
    role: 'ADC',
    tags: ['Marksman', 'Waveclear'],
    stats: { range: 7, burst: 6, cc: 1, mobility: 6, waveclear: 9, scaling: 8 },
    synergies: ['Poke_Siege', 'Objective_Control'],
  },
  {
    id: 'Smolder',
    name: 'Smolder',
    role: 'ADC',
    tags: ['Marksman', 'Scaling'],
    stats: { range: 8, burst: 5, cc: 1, mobility: 4, waveclear: 7, scaling: 10 },
    synergies: ['Hypercarry', 'Poke_Siege'],
  },
  {
    id: 'Swain',
    name: 'Swain',
    role: 'ADC',
    tags: ['Mage', 'Teamfight'],
    stats: { range: 7, burst: 7, cc: 7, mobility: 2, waveclear: 7, scaling: 8 },
    synergies: ['Front_to_Back', 'Aoe_Damage'],
  },
  {
    id: 'Syndra',
    name: 'Syndra',
    role: 'ADC',
    tags: ['Burst Mage', 'Pick'],
    stats: { range: 9, burst: 9, cc: 6, mobility: 2, waveclear: 8, scaling: 8 },
    synergies: ['Pick', 'Poke_Siege'],
  },
  {
    id: 'Taliyah',
    name: 'Taliyah',
    role: 'ADC',
    tags: ['Mage', 'Roam'],
    stats: { range: 9, burst: 8, cc: 6, mobility: 5, waveclear: 8, scaling: 7 },
    synergies: ['Zone_Control', 'Global_Pressure'],
  },
  {
    id: 'Tristana',
    name: 'Tristana',
    role: 'ADC',
    tags: ['Marksman', 'Siege'],
    stats: { range: 9, burst: 8, cc: 2, mobility: 7, waveclear: 8, scaling: 9 },
    synergies: ['Poke_Siege', 'Snowball'],
  },
  {
    id: 'Twitch',
    name: 'Twitch',
    role: 'ADC',
    tags: ['Marksman', 'Stealth'],
    stats: { range: 9, burst: 7, cc: 1, mobility: 4, waveclear: 6, scaling: 9 },
    synergies: ['Flank', 'Hypercarry'],
  },
  {
    id: 'Varus',
    name: 'Varus',
    role: 'ADC',
    tags: ['Marksman', 'Poke'],
    stats: { range: 9, burst: 8, cc: 6, mobility: 2, waveclear: 8, scaling: 8 },
    synergies: ['Pick', 'Poke_Siege'],
  },
  {
    id: 'Vayne',
    name: 'Vayne',
    role: 'ADC',
    tags: ['Marksman', 'Duelist'],
    stats: { range: 7, burst: 6, cc: 2, mobility: 8, waveclear: 3, scaling: 10 },
    synergies: ['Hypercarry', 'Duelist'],
  },
  {
    id: 'Veigar',
    name: 'Veigar',
    role: 'ADC',
    tags: ['Burst Mage', 'Scaling'],
    stats: { range: 8, burst: 10, cc: 9, mobility: 1, waveclear: 7, scaling: 10 },
    synergies: ['Pick', 'Zone_Control'],
  },
  {
    id: 'Xayah',
    name: 'Xayah',
    role: 'ADC',
    tags: ['Marksman', 'Teamfight'],
    stats: { range: 8, burst: 8, cc: 5, mobility: 5, waveclear: 8, scaling: 8 },
    synergies: ['Front_to_Back', 'Self_Peel'],
  },
  {
    id: 'Yasuo',
    name: 'Yasuo',
    role: 'ADC',
    tags: ['Skirmisher', 'Carry'],
    stats: { range: 1, burst: 8, cc: 4, mobility: 9, waveclear: 8, scaling: 8 },
    synergies: ['Knockup_Combo', 'Duelist'],
  },
  {
    id: 'Yunara',
    name: 'Yunara',
    role: 'ADC',
    tags: ['Marksman', 'Scaling'],
    stats: { range: 8, burst: 7, cc: 3, mobility: 5, waveclear: 7, scaling: 9 },
    synergies: ['Front_to_Back', 'Hypercarry'],
  },
  {
    id: 'Zeri',
    name: 'Zeri',
    role: 'ADC',
    tags: ['Marksman', 'Skirmisher'],
    stats: { range: 8, burst: 6, cc: 2, mobility: 9, waveclear: 7, scaling: 9 },
    synergies: ['Kite', 'Hypercarry'],
  },
  {
    id: 'Ziggs',
    name: 'Ziggs',
    role: 'ADC',
    tags: ['Mage', 'Siege'],
    stats: { range: 10, burst: 8, cc: 3, mobility: 2, waveclear: 10, scaling: 8 },
    synergies: ['Poke_Siege', 'Objective_Control'],
  },
]

const SUPPORT_CHAMPIONS = [
  {
    id: 'Alistar',
    name: 'Alistar',
    role: 'Support',
    tags: ['Tank', 'Engage'],
    stats: { range: 1, burst: 4, cc: 10, mobility: 5, waveclear: 2, scaling: 7 },
    synergies: ['Engage', 'CC_Chain'],
  },
  {
    id: 'Ashe',
    name: 'Ashe',
    role: 'Support',
    tags: ['Utility', 'Poke'],
    stats: { range: 8, burst: 4, cc: 8, mobility: 2, waveclear: 4, scaling: 6 },
    synergies: ['Pick', 'Poke_Siege'],
  },
  {
    id: 'Bard',
    name: 'Bard',
    role: 'Support',
    tags: ['Roam', 'Utility'],
    stats: { range: 8, burst: 5, cc: 7, mobility: 8, waveclear: 3, scaling: 7 },
    synergies: ['Global_Pressure', 'Pick'],
  },
  {
    id: 'Blitzcrank',
    name: 'Blitzcrank',
    role: 'Support',
    tags: ['Pick', 'Tank'],
    stats: { range: 5, burst: 6, cc: 9, mobility: 4, waveclear: 2, scaling: 6 },
    synergies: ['Pick', 'CC_Chain'],
  },
  {
    id: 'Braum',
    name: 'Braum',
    role: 'Support',
    tags: ['Tank', 'Protect'],
    stats: { range: 3, burst: 3, cc: 8, mobility: 3, waveclear: 2, scaling: 8 },
    synergies: ['Protect_Carry', 'Front_to_Back'],
  },
  {
    id: 'Heimerdinger',
    name: 'Heimerdinger',
    role: 'Support',
    tags: ['Mage', 'Siege'],
    stats: { range: 8, burst: 7, cc: 4, mobility: 2, waveclear: 7, scaling: 7 },
    synergies: ['Zone_Control', 'Poke_Siege'],
  },
  {
    id: 'Janna',
    name: 'Janna',
    role: 'Support',
    tags: ['Enchanter', 'Disengage'],
    stats: { range: 7, burst: 3, cc: 7, mobility: 7, waveclear: 3, scaling: 8 },
    synergies: ['Protect_Carry', 'Disengage'],
  },
  {
    id: 'Karma',
    name: 'Karma',
    role: 'Support',
    tags: ['Enchanter', 'Poke'],
    stats: { range: 8, burst: 6, cc: 5, mobility: 5, waveclear: 4, scaling: 7 },
    synergies: ['Poke_Siege', 'Protect_Carry'],
  },
  {
    id: 'Leona',
    name: 'Leona',
    role: 'Support',
    tags: ['Tank', 'Engage'],
    stats: { range: 1, burst: 4, cc: 10, mobility: 6, waveclear: 2, scaling: 7 },
    synergies: ['Engage', 'CC_Chain'],
  },
  {
    id: 'Lulu',
    name: 'Lulu',
    role: 'Support',
    tags: ['Enchanter', 'Utility'],
    stats: { range: 7, burst: 4, cc: 7, mobility: 4, waveclear: 3, scaling: 9 },
    synergies: ['Protect_Carry', 'Hypercarry'],
  },
  {
    id: 'Lux',
    name: 'Lux',
    role: 'Support',
    tags: ['Mage', 'Pick'],
    stats: { range: 10, burst: 8, cc: 8, mobility: 2, waveclear: 5, scaling: 7 },
    synergies: ['Pick', 'Poke_Siege'],
  },
  {
    id: 'Maokai',
    name: 'Maokai',
    role: 'Support',
    tags: ['Tank', 'Control'],
    stats: { range: 2, burst: 4, cc: 9, mobility: 3, waveclear: 3, scaling: 7 },
    synergies: ['CC_Chain', 'Vision_Control'],
  },
  {
    id: 'Milio',
    name: 'Milio',
    role: 'Support',
    tags: ['Enchanter', 'Protect'],
    stats: { range: 8, burst: 2, cc: 5, mobility: 4, waveclear: 2, scaling: 8 },
    synergies: ['Protect_Carry', 'Hypercarry'],
  },
  {
    id: 'Morgana',
    name: 'Morgana',
    role: 'Support',
    tags: ['Mage', 'Control'],
    stats: { range: 8, burst: 6, cc: 8, mobility: 3, waveclear: 4, scaling: 7 },
    synergies: ['Pick', 'Disengage'],
  },
  {
    id: 'Nami',
    name: 'Nami',
    role: 'Support',
    tags: ['Enchanter', 'Engage'],
    stats: { range: 7, burst: 4, cc: 7, mobility: 5, waveclear: 3, scaling: 8 },
    synergies: ['Engage', 'Protect_Carry'],
  },
  {
    id: 'Nautilus',
    name: 'Nautilus',
    role: 'Support',
    tags: ['Tank', 'Engage'],
    stats: { range: 2, burst: 4, cc: 10, mobility: 5, waveclear: 2, scaling: 7 },
    synergies: ['CC_Chain', 'Pick'],
  },
  {
    id: 'Neeko',
    name: 'Neeko',
    role: 'Support',
    tags: ['Mage', 'Engage'],
    stats: { range: 8, burst: 8, cc: 8, mobility: 4, waveclear: 4, scaling: 7 },
    synergies: ['Engage', 'Aoe_Damage'],
  },
  {
    id: 'Pantheon',
    name: 'Pantheon',
    role: 'Support',
    tags: ['Bruiser', 'Early Game'],
    stats: { range: 2, burst: 8, cc: 4, mobility: 6, waveclear: 2, scaling: 4 },
    synergies: ['Dive', 'Snowball'],
  },
  {
    id: 'Poppy',
    name: 'Poppy',
    role: 'Support',
    tags: ['Tank', 'Anti-Dash'],
    stats: { range: 1, burst: 5, cc: 8, mobility: 4, waveclear: 2, scaling: 7 },
    synergies: ['Disengage', 'CC_Chain'],
  },
  {
    id: 'Pyke',
    name: 'Pyke',
    role: 'Support',
    tags: ['Assassin', 'Pick'],
    stats: { range: 2, burst: 8, cc: 7, mobility: 9, waveclear: 2, scaling: 6 },
    synergies: ['Pick', 'Cleanup'],
  },
  {
    id: 'Rakan',
    name: 'Rakan',
    role: 'Support',
    tags: ['Engage', 'Utility'],
    stats: { range: 2, burst: 4, cc: 8, mobility: 9, waveclear: 2, scaling: 7 },
    synergies: ['Engage', 'Dive'],
  },
  {
    id: 'Rell',
    name: 'Rell',
    role: 'Support',
    tags: ['Tank', 'Engage'],
    stats: { range: 1, burst: 4, cc: 10, mobility: 5, waveclear: 2, scaling: 7 },
    synergies: ['Engage', 'Aoe_Damage'],
  },
  {
    id: 'RenataGlasc',
    name: 'Renata Glasc',
    role: 'Support',
    tags: ['Enchanter', 'Control'],
    stats: { range: 7, burst: 4, cc: 8, mobility: 3, waveclear: 2, scaling: 8 },
    synergies: ['Disengage', 'Protect_Carry'],
  },
  {
    id: 'Senna',
    name: 'Senna',
    role: 'Support',
    tags: ['Marksman', 'Utility'],
    stats: { range: 10, burst: 6, cc: 6, mobility: 3, waveclear: 3, scaling: 8 },
    synergies: ['Pick', 'Poke_Siege'],
  },
  {
    id: 'Seraphine',
    name: 'Seraphine',
    role: 'Support',
    tags: ['Enchanter', 'Mage'],
    stats: { range: 9, burst: 5, cc: 8, mobility: 2, waveclear: 4, scaling: 8 },
    synergies: ['Aoe_Damage', 'Front_to_Back'],
  },
  {
    id: 'Shaco',
    name: 'Shaco',
    role: 'Support',
    tags: ['Trickster', 'Pick'],
    stats: { range: 2, burst: 7, cc: 5, mobility: 8, waveclear: 3, scaling: 5 },
    synergies: ['Vision_Control', 'Pick'],
  },
  {
    id: 'Sona',
    name: 'Sona',
    role: 'Support',
    tags: ['Enchanter', 'Scaling'],
    stats: { range: 7, burst: 3, cc: 6, mobility: 4, waveclear: 2, scaling: 9 },
    synergies: ['Protect_Carry', 'Front_to_Back'],
  },
  {
    id: 'Soraka',
    name: 'Soraka',
    role: 'Support',
    tags: ['Enchanter', 'Heal'],
    stats: { range: 7, burst: 2, cc: 5, mobility: 3, waveclear: 2, scaling: 9 },
    synergies: ['Protect_Carry', 'Sustain'],
  },
  {
    id: 'Swain',
    name: 'Swain',
    role: 'Support',
    tags: ['Mage', 'Teamfight'],
    stats: { range: 7, burst: 7, cc: 7, mobility: 2, waveclear: 4, scaling: 8 },
    synergies: ['Aoe_Damage', 'Front_to_Back'],
  },
  {
    id: 'TahmKench',
    name: 'Tahm Kench',
    role: 'Support',
    tags: ['Tank', 'Protect'],
    stats: { range: 2, burst: 4, cc: 7, mobility: 3, waveclear: 2, scaling: 8 },
    synergies: ['Protect_Carry', 'Disengage'],
  },
  {
    id: 'Taric',
    name: 'Taric',
    role: 'Support',
    tags: ['Tank', 'Enchanter'],
    stats: { range: 1, burst: 3, cc: 7, mobility: 3, waveclear: 2, scaling: 8 },
    synergies: ['Protect_Carry', 'Front_to_Back'],
  },
  {
    id: 'Thresh',
    name: 'Thresh',
    role: 'Support',
    tags: ['Tank', 'Pick'],
    stats: { range: 5, burst: 5, cc: 9, mobility: 5, waveclear: 2, scaling: 8 },
    synergies: ['Pick', 'Disengage'],
  },
  {
    id: 'VelKoz',
    name: "Vel'Koz",
    role: 'Support',
    tags: ['Mage', 'Poke'],
    stats: { range: 10, burst: 8, cc: 6, mobility: 1, waveclear: 4, scaling: 7 },
    synergies: ['Poke_Siege', 'Pick'],
  },
  {
    id: 'Xerath',
    name: 'Xerath',
    role: 'Support',
    tags: ['Mage', 'Poke'],
    stats: { range: 10, burst: 8, cc: 5, mobility: 1, waveclear: 4, scaling: 7 },
    synergies: ['Poke_Siege', 'Zone_Control'],
  },
  {
    id: 'Yuumi',
    name: 'Yuumi',
    role: 'Support',
    tags: ['Enchanter', 'Attach'],
    stats: { range: 7, burst: 2, cc: 6, mobility: 8, waveclear: 1, scaling: 8 },
    synergies: ['Protect_Carry', 'Hypercarry'],
  },
  {
    id: 'Zac',
    name: 'Zac',
    role: 'Support',
    tags: ['Tank', 'Engage'],
    stats: { range: 2, burst: 5, cc: 9, mobility: 7, waveclear: 2, scaling: 7 },
    synergies: ['Engage', 'CC_Chain'],
  },
  {
    id: 'Zilean',
    name: 'Zilean',
    role: 'Support',
    tags: ['Utility', 'Control'],
    stats: { range: 8, burst: 5, cc: 7, mobility: 4, waveclear: 3, scaling: 8 },
    synergies: ['Protect_Carry', 'Pick'],
  },
  {
    id: 'Zyra',
    name: 'Zyra',
    role: 'Support',
    tags: ['Mage', 'Control'],
    stats: { range: 9, burst: 7, cc: 6, mobility: 2, waveclear: 4, scaling: 7 },
    synergies: ['Zone_Control', 'Pick'],
  },
]

function clampToTen(value) {
  return Math.max(1, Math.min(10, Math.round(value)))
}

function deriveSupportArchetype(champion) {
  if (champion.tags.includes('Enchanter')) {
    return 'Enchanter'
  }

  if (
    champion.tags.includes('Tank') ||
    champion.tags.includes('Engage') ||
    champion.synergies.includes('Engage')
  ) {
    return 'Engage Tank'
  }

  return 'Specialist'
}

const ADC_CHAMPIONS_WITH_DUO = ADC_CHAMPIONS.map((champion) => {
  const baseDps =
    champion.stats.scaling * 0.45 + champion.stats.burst * 0.35 + champion.stats.waveclear * 0.2
  const dpsBonus = champion.tags.includes('Hypercarry') ? 1 : 0

  const basePositioning =
    champion.stats.mobility * 0.5 + champion.stats.range * 0.35 + champion.stats.cc * 0.15
  const positioningBonus = champion.synergies.includes('Self_Peel') ? 1 : 0

  const baseAttackSpeedScaling = champion.stats.scaling * 0.7 + champion.stats.mobility * 0.2
  const attackSpeedBonus = (champion.tags.includes('Hypercarry') ? 0.7 : 0) +
    (champion.tags.includes('Marksman') ? 0.3 : 0)

  return {
    ...champion,
    adcStats: {
      DPS: clampToTen(baseDps + dpsBonus),
      Positioning: clampToTen(basePositioning + positioningBonus),
      AttackSpeedScaling: clampToTen(baseAttackSpeedScaling + attackSpeedBonus),
    },
  }
})

const SUPPORT_CHAMPIONS_WITH_DUO = SUPPORT_CHAMPIONS.map((champion) => {
  const supportArchetype = deriveSupportArchetype(champion)

  const baseVision =
    champion.stats.cc * 0.35 + champion.stats.range * 0.25 + champion.stats.mobility * 0.25 +
    champion.stats.waveclear * 0.15
  const visionBonus = champion.synergies.includes('Vision_Control') ? 1 : 0

  const basePeel = champion.stats.cc * 0.45 + champion.stats.mobility * 0.25 + champion.stats.scaling * 0.3
  const peelBonus =
    (champion.synergies.includes('Protect_Carry') ? 1 : 0) +
    (champion.synergies.includes('Disengage') ? 1 : 0) +
    (supportArchetype === 'Enchanter' ? 1 : 0)

  const baseEngage = champion.stats.cc * 0.55 + champion.stats.mobility * 0.25 + champion.stats.burst * 0.2
  const engageBonus =
    (champion.tags.includes('Engage') ? 1 : 0) +
    (champion.tags.includes('Tank') ? 1 : 0) +
    (supportArchetype === 'Engage Tank' ? 1 : 0)

  return {
    ...champion,
    supportArchetype,
    supportStats: {
      VisionScore: clampToTen(baseVision + visionBonus),
      Peel: clampToTen(basePeel + peelBonus),
      Engage: clampToTen(baseEngage + engageBonus),
    },
  }
})

export const SUPPORT_ENCHANTERS = SUPPORT_CHAMPIONS_WITH_DUO.filter(
  (champion) => champion.supportArchetype === 'Enchanter',
)

export const SUPPORT_ENGAGE_TANKS = SUPPORT_CHAMPIONS_WITH_DUO.filter(
  (champion) => champion.supportArchetype === 'Engage Tank',
)

export const SUPPORT_SPECIALISTS = SUPPORT_CHAMPIONS_WITH_DUO.filter(
  (champion) => champion.supportArchetype === 'Specialist',
)

export const BOTLANE_DUO_JSON = {
  adcs: ADC_CHAMPIONS_WITH_DUO,
  supports: {
    all: SUPPORT_CHAMPIONS_WITH_DUO,
    enchanters: SUPPORT_ENCHANTERS,
    engageTanks: SUPPORT_ENGAGE_TANKS,
    specialists: SUPPORT_SPECIALISTS,
  },
}

export const CHAMPION_SCHEMA_KEYS = {
  root: [
    'id',
    'name',
    'role',
    'tags',
    'stats',
    'synergies',
    'jungleStats',
    'midlaneStats',
    'adcStats',
    'supportArchetype',
    'supportStats',
  ],
  stats: ['range', 'burst', 'cc', 'mobility', 'waveclear', 'scaling'],
  jungleStats: ['ClearSpeed', 'GankPressure', 'ObjectiveControl'],
  midlaneStats: ['RoamPotential', 'LanePriority', 'ManaManagement', 'EnergyManagement'],
  adcStats: ['DPS', 'Positioning', 'AttackSpeedScaling'],
  supportStats: ['VisionScore', 'Peel', 'Engage'],
}

export const CHAMPIONS_DB = [
  ...TOPLANE_CHAMPIONS,
  ...JUNGLE_CHAMPIONS_WITH_PATHING,
  ...MIDLANE_CHAMPIONS_WITH_MACRO,
  ...ADC_CHAMPIONS_WITH_DUO,
  ...SUPPORT_CHAMPIONS_WITH_DUO,
]

export const CHAMPIONS_BY_ROLE = CHAMPIONS_DB.reduce((acc, champion) => {
  if (!acc[champion.role]) {
    acc[champion.role] = []
  }

  acc[champion.role].push(champion)
  return acc
}, {})

export const CHAMPION_TAG_INDEX = CHAMPIONS_DB.reduce((acc, champion) => {
  champion.tags.forEach((tag) => {
    if (!acc[tag]) {
      acc[tag] = []
    }

    acc[tag].push(champion.id)
  })

  return acc
}, {})

export const NO_LUCK_COMBOS = [
  {
    id: 'THE_WALL',
    name: 'Le Mur',
    requirements: ['Malphite', 'Maokai'],
    bonus: {
      stat: 'group_survivability',
      value: 0.15,
      label: '+15% survie de groupe',
    },
  },
  {
    id: 'FULL_GLOBAL',
    name: 'Full Global',
    requirements: ['Shen', 'Galio', 'Nocturne'],
    bonus: {
      stat: 'macro',
      value: 0.2,
      label: '+20% macro',
    },
  },
]
